# Generated by Django 5.1.15 on 2026-10-09 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0015_user_phone_key_index'),
        ('notifications', '0004_seed_permissions'),
        ('student', '0006_parent_phone_key_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('event', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], default='telegram', max_length=20)),
                ('chat_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': '"notification"."notification_deliveries"',
            },
        ),
        migrations.CreateModel(
            name='ParentTelegramLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('chat_id', models.BigIntegerField()),
                ('telegram_user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"notification"."parent_telegram_links"',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key__isnull', False)), fields=('recipient', 'event_key'), name='uq_notif_recipient_event'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='notification',
            field=models.ForeignKey(blank=True, db_column='notification_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='recipient_user',
            field=models.ForeignKey(blank=True, db_column='recipient_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='student_parent',
            field=models.ForeignKey(blank=True, db_column='student_parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='student.studentparent'),
        ),
        migrations.AddField(
            model_name='parenttelegramlink',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization'),
        ),
        migrations.AddField(
            model_name='parenttelegramlink',
            name='student_parent',
            field=models.OneToOneField(db_column='student_parent_id', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to='student.studentparent'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['next_attempt_at'], name='idx_deliveries_pending'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['organization', '-created_at'], name='idx_deliveries_org'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recipient_user__isnull', False), ('student_parent__isnull', True)), models.Q(('recipient_user__isnull', True), ('student_parent__isnull', False)), _connector='OR'), name='chk_deliveries_one_recipient'),
        ),
        migrations.AddIndex(
            model_name='parenttelegramlink',
            index=models.Index(fields=['chat_id'], name='idx_parent_tg_links_chat'),
        ),
    ]
