# Generated by Django 5.1.15 on 2026-10-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_delivery_triggers_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='parenttelegramlink',
            name='verified_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
