# Generated by Django 5.1.15 on 2026-08-25 08:59
#
# Super-Admin Settings' Backup + API Keys panels — see
# foundation/models/platform_backup.py and api_key.py's docstrings for why
# both are platform-global (no `organization` FK) and, like `Permission`,
# deliberately not added to RLS_TABLES (migrations/0004_rls.py) — gated
# purely by the `platform_settings` permission check in the view. The
# `updated_at` trigger for both tables is 0013_platform_backup_and_api_key_triggers.py,
# same split as every other app's 0001_initial + 0002_triggers pair.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0011_seed_platform_settings_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=255)),
                ('key_prefix', models.CharField(max_length=20)),
                ('key_hash', models.CharField(max_length=64)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"foundation"."api_keys"',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash'], name='idx_api_keys_hash'), models.Index(fields=['-created_at'], name='idx_api_keys_created')],
            },
        ),
        migrations.CreateModel(
            name='PlatformBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('storage_path', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"foundation"."platform_backups"',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_platform_backups_created')],
            },
        ),
    ]
