# Generated by Django 5.1.15 on 2026-10-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0013_platform_backup_and_api_key_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
