# Generated by Django 5.1.15 on 2026-10-09 18:58

import common.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0014_user_must_change_password'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(common.db.PhoneKey('phone'), condition=models.Q(('deleted_at__isnull', True)), name='idx_users_phone_key'),
        ),
    ]
