# Generated by Django 5.1.15 on 2026-10-08 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0005_remove_email_verification'),
        ('foundation', '0014_user_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('chat_id', models.BigIntegerField()),
                ('telegram_user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('verified_phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"auth"."telegram_accounts"',
            },
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='attempts',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram')], default='telegram', max_length=20),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='code_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='codes_sent',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(condition=models.Q(('telegram_chat_id__isnull', False), ('used_at__isnull', True)), fields=['telegram_chat_id', '-created_at'], name='idx_password_resets_tg_chat'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['chat_id'], name='idx_telegram_accounts_chat'),
        ),
    ]
