# Generated by Django 5.1.15 on 2026-10-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0007_telegram_accounts_trigger_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChatState',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('intent', models.CharField(choices=[('reset', 'Password reset'), ('connect', 'Connect notifications')], max_length=20)),
                ('intent_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"auth"."telegram_chat_states"',
            },
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
