# Generated by Django 5.1.15 on 2026-10-07 16:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_grant_student_finance_view'),
        ('foundation', '0013_platform_backup_and_api_key_triggers'),
        ('teacher', '0006_seed_teacher_salary_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('salaries_other', 'Salaries (Other Staff)'), ('supplies', 'Supplies'), ('marketing', 'Marketing'), ('maintenance', 'Maintenance'), ('equipment', 'Equipment'), ('software', 'Software'), ('taxes', 'Taxes'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='foundation.branch')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
            ],
            options={
                'db_table': '"finance"."expenses"',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_expenses_org'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_expenses_status'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'expense_date'], name='idx_expenses_date'), models.Index(condition=models.Q(('branch__isnull', False), ('deleted_at__isnull', True)), fields=['branch'], name='idx_expenses_branch')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_expenses_amount')],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('teacher_profile', models.ForeignKey(db_column='teacher_profile_id', on_delete=django.db.models.deletion.RESTRICT, related_name='payroll_records', to='teacher.teacherprofile')),
            ],
            options={
                'db_table': '"finance"."payroll"',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'period_start'], name='idx_payroll_org_period'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['teacher_profile', 'period_start'], name='idx_payroll_teacher'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_payroll_status')],
                'constraints': [models.UniqueConstraint(fields=('teacher_profile', 'period_start', 'period_end'), name='uq_payroll_teacher_period'), models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='chk_payroll_period'), models.CheckConstraint(condition=models.Q(('base_salary__gte', 0), ('bonus__gte', 0), ('deductions__gte', 0), ('tax_amount__gte', 0)), name='chk_payroll_amounts')],
            },
        ),
    ]
