# Generated by Django 5.1.15 on 2026-10-07 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
