# Generated by Django 5.1.15 on 2026-10-09 18:58

import common.db
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0015_user_phone_key_index'),
        ('student', '0005_grant_student_self_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentparent',
            index=models.Index(common.db.PhoneKey('phone'), condition=models.Q(('deleted_at__isnull', True)), name='idx_student_parents_phone_key'),
        ),
    ]
